--liquibase formatted sql

--changeset sharov:1
CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name VARCHAR(255) NOT NULL ,
    username VARCHAR(255) UNIQUE ,
    lastname VARCHAR(255) NOT NULL ,
    email VARCHAR(255) UNIQUE ,
    bio TEXT,
    password VARCHAR(1500),
    created_date TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS users_role
(
    users_id BIGINT REFERENCES users(id),
    role SMALLINT
);

CREATE TABLE IF NOT EXISTS post
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    title VARCHAR(255),
    caption VARCHAR(255),
    location VARCHAR(255),
    likes INTEGER,
    users_id BIGINT REFERENCES users(id),
    created_date TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS comment
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    post_id BIGINT REFERENCES post(id),
    username VARCHAR(64) NOT NULL,
    users_id BIGINT  NOT NULL,
    message TEXT NOT NULL ,
    created_date TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS image
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    name VARCHAR(255),
    image_bytes BYTEA,
    users_id BIGINT,
    post_id BIGINT
);

CREATE TABLE IF NOT EXISTS post_liked_users
(
    post_id BIGINT REFERENCES post(id),
    liked_users VARCHAR(255)
);